import fs from "node:fs";
import path from "node:path";
import { defaultSwiftBarPluginDir, ensureDir, expandHome } from "../core/paths.js";

function combinedPluginName(refreshSeconds) {
  const sec = Math.max(15, Number(refreshSeconds) || 30);
  return `headroom-combined.${sec}s.sh`;
}

function normalizeAccount(a) {
  const menubar = a?.menubar !== false;
  return {
    id: a.id,
    label: a.label || a.id,
    provider: a.provider,
    order: a.order ?? 100,
    menubar,
    showInBar: a.showInBar != null ? !!a.showInBar : menubar,
    showInDetail: a.showInDetail != null ? !!a.showInDetail : menubar,
  };
}

function resolveMenubarLocale(settings = {}) {
  const setting = String(settings.locale || "system").toLowerCase();
  if (setting === "tr" || setting === "en") return setting;
  // system: infer from process env LANG/LC_ALL at generation time
  const env = `${process.env.LC_ALL || ""} ${process.env.LANG || ""} ${process.env.LC_MESSAGES || ""}`.toLowerCase();
  if (env.includes("tr_") || env.startsWith("tr") || env.includes(".tr")) return "tr";
  return "en";
}

export function renderCombinedSwiftBarPlugin({ accounts, endpoint, settings = {} }) {
  const selected = (accounts || [])
    .map(normalizeAccount)
    .filter((a) => a.menubar && (a.showInBar || a.showInDetail))
    .sort((a, b) => a.order - b.order);

  const base = String(endpoint || "http://127.0.0.1:8787").replace(/\/$/, "");
  const mode = settings.menubarMode === "compact" ? "compact" : "detail";
  const join = settings.menubarJoin || " · ";
  const emptyTitle = settings.menubarEmptyTitle || "HR";
  const locale = resolveMenubarLocale(settings);

  const lines = [];
  const p = (s) => lines.push(s);

  p("#!/bin/zsh");
  p("# <swiftbar.hideAbout>true</swiftbar.hideAbout>");
  p("# <swiftbar.hideRunInTerminal>true</swiftbar.hideRunInTerminal>");
  p("# <swiftbar.hideLastUpdated>true</swiftbar.hideLastUpdated>");
  p("# <swiftbar.hideDisablePlugin>true</swiftbar.hideDisablePlugin>");
  p("# <swiftbar.hideSwiftBar>true</swiftbar.hideSwiftBar>");
  p("# Generated by Headroom - no icons");
  p("");
  p("/usr/bin/python3 - <<'PY'");
  p("import json, os, urllib.parse, urllib.request");
  p("");
  p(`BASE = ${JSON.stringify(base)}`);
  p(`MODE = ${JSON.stringify(mode)}`);
  p(`JOIN = ${JSON.stringify(join)}`);
  p(`EMPTY = ${JSON.stringify(emptyTitle)}`);
  p(`LOCALE_SETTING = ${JSON.stringify(settings.locale || "system")}`);
  p(`ACCOUNTS = json.loads(${JSON.stringify(JSON.stringify(selected))})`);
  p("");
  p("def detect_locale():");
  p("    s = (LOCALE_SETTING or 'system').lower()");
  p("    if s in ('tr', 'en'):");
  p("        return s");
  p("    env = ' '.join([");
  p("        os.environ.get('LC_ALL',''),");
  p("        os.environ.get('LANG',''),");
  p("        os.environ.get('LC_MESSAGES',''),");
  p("    ]).lower()");
  p("    if 'tr_' in env or env.startswith('tr') or '.tr' in env:");
  p("        return 'tr'");
  p("    # macOS UI language fallback");
  p("    try:");
  p("        import subprocess");
  p("        out = subprocess.check_output(['defaults', 'read', '-g', 'AppleLocale'], text=True).strip().lower()");
  p("        if out.startswith('tr') or 'tr_' in out:");
  p("            return 'tr'");
  p("    except Exception:");
  p("        pass");
  p("    return 'en'");
  p("");
  p("LOC = detect_locale()");
  p("T = {");
  p("  'en': {");
  p("    'error': 'error',");
  p("    'no_data': 'no data',");
  p("    'remaining': 'Remaining: %%%s',");
  p("    'used': 'Used: %%%s',");
  p("    'reset': 'Reset at: %s',");
  p("    'plan': 'Plan: %s',");
  p("    'account': 'Account: %s',");
  p("    'source': 'Source: %s',");
  p("    'compact': '%s: %%%s remaining',");
  p("    'open': 'Open Headroom panel',");
  p("    'refresh': 'Refresh',");
  p("    'reset_action': 'Reset',");
  p("    'close': 'Close',");
  p("  },");
  p("  'tr': {");
  p("    'error': 'hata',");
  p("    'no_data': 'veri yok',");
  p("    'remaining': 'Kalan: %%%s',");
  p("    'used': 'Tüketilen: %%%s',");
  p("    'reset': 'Sıfırlanma: %s',");
  p("    'plan': 'Plan: %s',");
  p("    'account': 'Hesap: %s',");
  p("    'source': 'Kaynak: %s',");
  p("    'compact': '%s: %%%s kalan',");
  p("    'open': 'Headroom panelini aç',");
  p("    'refresh': 'Yenile',");
  p("    'reset_action': 'Sıfırla',");
  p("    'close': 'Kapat',");
  p("  },");
  p("}[LOC]");
  p("");
  p("def get(url, timeout=8):");
  p("    with urllib.request.urlopen(url, timeout=timeout) as r:");
  p("        return json.loads(r.read().decode('utf-8'))");
  p("");
  p("def safe(s):");
  p("    return str(s).replace('|', '\\\\|').replace('\\n', ' ')");
  p("");
  p("rows = []");
  p("for acc in ACCOUNTS:");
  p("    item = {");
  p("        'id': acc.get('id'),");
  p("        'label': acc.get('label') or acc.get('id') or '?',");
  p("        'showInBar': bool(acc.get('showInBar')),");
  p("        'showInDetail': bool(acc.get('showInDetail')),");
  p("        'remaining': None,");
  p("        'used': None,");
  p("        'resetAt': None,");
  p("        'plan': None,");
  p("        'email': None,");
  p("        'source': None,");
  p("        'error': None,");
  p("    }");
  p("    try:");
  p("        qid = urllib.parse.quote(str(acc.get('id') or ''))");
  p("        data = get('%s/api/quota/%s' % (BASE, qid))");
  p("        if data.get('error'):");
  p("            item['error'] = data.get('error')");
  p("        else:");
  p("            item['remaining'] = data.get('remainingPercent')");
  p("            item['used'] = data.get('usedPercent')");
  p("            item['resetAt'] = data.get('resetAt')");
  p("            item['plan'] = data.get('plan')");
  p("            item['email'] = data.get('email')");
  p("            item['source'] = data.get('source')");
  p("    except Exception as exc:");
  p("        item['error'] = 'offline: %s' % exc");
  p("    rows.append(item)");
  p("");
  p("bar_rows = [r for r in rows if r.get('showInBar')]");
  p("detail_rows = [r for r in rows if r.get('showInDetail')]");
  p("if not detail_rows:");
  p("    detail_rows = rows");
  p("");
  p("if not bar_rows:");
  p("    print(EMPTY)");
  p("else:");
  p("    chips = []");
  p("    for r in bar_rows:");
  p("        if r['error'] is not None or r['remaining'] is None:");
  p("            chips.append('%s ?' % r['label'])");
  p("        else:");
  p("            chips.append('%s %s%%' % (r['label'], int(round(r['remaining']))))");
  p("    print(JOIN.join(chips))");
  p("");
  p("print('---')");
  p("for r in detail_rows:");
  p("    label = safe(r['label'])");
  p("    # Top-level active rows (not only nested --), so details are visible/clickable.");
  p("    if r['error'] is not None or r['remaining'] is None:");
  p("        print('%s: %s | href=%s/ color=red' % (label, T['error'], BASE))");
  p("        print('-- %s' % safe(r['error'] or T['no_data']))");
  p("        continue");
  p("    rem = int(round(r['remaining']))");
  p("    used = int(round(r['used'])) if r['used'] is not None else None");
  p("    used_txt = (' · used %s%%' % used) if used is not None else ''");
  p("    reset_txt = (' · ' + safe(r['resetAt'])) if r.get('resetAt') else ''");
  p("    # Active detail line opens dashboard");
  p("    print('%s %s%%%s%s | href=%s/ refresh=true' % (label, rem, used_txt, reset_txt, BASE))");
  p("    print('-- ' + (T['remaining'] % rem))");
  p("    if used is not None:");
  p("        print('-- ' + (T['used'] % used))");
  p("    if r.get('resetAt'):");
  p("        print('-- ' + (T['reset'] % safe(r['resetAt'])))");
  p("    if r.get('plan'):");
  p("        print('-- ' + (T['plan'] % safe(r['plan'])))");
  p("    if r.get('email'):");
  p("        print('-- ' + (T['account'] % safe(r['email'])))");
  p("    if r.get('source'):");
  p("        print('-- ' + (T['source'] % safe(r['source'])))");
  p("    print('-- %s | href=%s/ terminal=false' % (T['open'], BASE))");
  p("");
  p("print('---')");
  p("print('%s | href=%s/' % (T['open'], BASE))");
  p("print('%s | refresh=true' % T['refresh'])");
  p("print('%s | bash=/usr/bin/curl param1=-sS param2=-X param3=POST param4=%s/api/swiftbar/reset terminal=false refresh=true' % (T['reset_action'], BASE))");
  p("print('%s | bash=/usr/bin/curl param1=-sS param2=-X param3=POST param4=%s/api/swiftbar/close terminal=false refresh=true' % (T['close'], BASE))");
  p("PY");
  p("");
  return lines.join("\n");
}

export function syncSwiftBarPlugins({ config, endpoint }) {
  const dir = expandHome(config.settings.swiftbarPluginDir || defaultSwiftBarPluginDir());
  ensureDir(dir);

  const refreshSeconds = config.settings.refreshSeconds || 30;
  const included = (config.accounts || []).filter((a) => a.menubar !== false);

  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    if (name.startsWith("headroom-") && name.endsWith(".sh")) {
      fs.unlinkSync(full);
      continue;
    }
    // leftover accidental dirs from older generators
    if (name === "Users") {
      fs.rmSync(full, { recursive: true, force: true });
    }
  }

  const barCount = included.filter((a) => (a.showInBar != null ? a.showInBar : true)).length;
  const detailCount = included.filter((a) => (a.showInDetail != null ? a.showInDetail : true)).length;

  if (included.length === 0) {
    return {
      dir,
      written: [],
      count: 0,
      selected: [],
      barCount,
      detailCount,
      mode: config.settings.menubarMode || "detail",
    };
  }

  const file = path.join(dir, combinedPluginName(refreshSeconds));
  const body = renderCombinedSwiftBarPlugin({
    accounts: included,
    endpoint,
    settings: config.settings || {},
  });
  fs.writeFileSync(file, body, { mode: 0o755 });
  fs.chmodSync(file, 0o755);

  return {
    dir,
    written: [file],
    count: 1,
    mode: config.settings.menubarMode || "detail",
    selected: included.map((a) => a.id),
    barCount,
    detailCount,
  };
}
